version: 0.2

phases:
  build:
    commands:
      - echo build started on 
      - date
      - dotnet build
  post_build:
    commands:
      - echo build completed on 
      - date
artifacts:
  files:
    - "**/*"
  name: mywebapp